#!/usr/bin/env bash

sudo esptool.py write_flash --port /dev/tty.SLAB_USBtoUART --erase-all --flash_freq 80m --flash_mode dio --flash_size 4MB --no-compress 0x00000 nodemcu-1.5.4.1-final-14-modules-2019-01-10-21-08-15-float.bin
